# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  test_data: true
  notebooks: false

jobs:

- job: Linux_Unit_Tests
  strategy:
    matrix:
      py38:
        conda_env: py38
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - template: ci/azure/unit-tests.yml

- job: Linux_Notebook_Tests
  strategy:
    matrix:
      py38:
        conda_env: py38-notebooks
        notebooks: true
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - template: ci/azure/notebook-tests.yml

- job: MacOSX_Unit_Tests
  strategy:
    matrix:
      py38:
        conda_env: py38
  pool:
    vmImage: 'macOS-10.15'
  steps:
  - template: ci/azure/unit-tests.yml

- job: Windows_Unit_Tests
  strategy:
    matrix:
      py38:
        conda_env: py38
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - template: ci/azure/unit-tests.yml