# Generated by Django 5.0.6 on 2024-05-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(decimal_places=18, max_digits=40)),
                ("longitude", models.DecimalField(decimal_places=18, max_digits=40)),
                ("height_tower", models.IntegerField(blank=True, null=True)),
                ("vertical_angle", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "image_beam",
                    models.ImageField(default="default.jpg", upload_to="senarios"),
                ),
                (
                    "image_couverture",
                    models.ImageField(default="default.jpg", upload_to="senarios"),
                ),
            ],
        ),
    ]
